sudo: false

language: haskell

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.stack

matrix:
  include:
  - env: BUILD=lts-8
    compiler: "GHC-8.0.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=lts-7
    compiler: "GHC-8.0.1"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=lts-6
    compiler: "GHC-7.10.3"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=hlint
    compiler: "GHC-8.0.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=stylish-haskell
    compiler: "GHC-8.0.2"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: BUILD=sdist
    compiler: "GHC-8.0.2"
    addons: {apt: {packages: [libgmp-dev]}}

before_install:
- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
- |
  set -ex
  mkdir -p ~/.local/bin
  travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  set +ex

install:
- |
  set -ex
  stack setup --upgrade-cabal && stack install --pedantic
  set +ex

script:
- |
  set -ex
  case "$BUILD" in
    lts-*)
      TEST_RESOLVER=$BUILD make test
      ;;
    hlint)
      make hlint
      ;;
    stylish-haskell)
      make stylish_haskell
      ;;
    sdist)
      make test_sdist
      ;;
  esac
  set +ex

notifications:
  email: false
